version: '3.8'
name: shortqix-development


services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${SQX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SQX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SQX_POSTGRES_DB}
    ports:
      - "${SQX_POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQX_POSTGRES_USER} -d ${SQX_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  smtp-server:
    image: 'datydock/mailslurper'

    ports:
      - 8080:8080
      - 8085:8085
      - 2500:2500
      
  database-client:
    container_name: database-client
    restart: always
    image: sosedoff/pgweb:0.16.2
    ports:
      - '8081:8081'
    environment:
      - PGWEB_DATABASE_URL=postgresql://${SQX_POSTGRES_USER}:${SQX_POSTGRES_PASSWORD}@host.docker.internal:${SQX_POSTGRES_PORT}/${SQX_POSTGRES_DB}?sslmode=disable
      - PGWEB_AUTH_USER=${SQX_POSTGRES_USER}
      - PGWEB_AUTH_PASS=${SQX_POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          '-u',
          '${SQX_POSTGRES_USER}:${SQX_POSTGRES_PASSWORD}',
          'http://localhost:8081/api/info',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s